let ord={},prices={};
function togLoc(){let d=document.querySelector('input[name="ot"]:checked').value==="delivery";document.getElementById("locf").style.display=d?"block":"none";document.getElementById("df").style.display=d?"block":"none";updSum()}
function updOrd(n,p,q){q=parseInt(q)||0;prices[n]=p;q>0?ord[n]=q:delete ord[n];updSum()}
function updSum(){let e=document.getElementById("sum"),s=0,d=document.querySelector('input[name="ot"]:checked').value==="delivery",df=d?20:0;if(!Object.keys(ord).length){e.innerHTML="<p>No items</p>";document.getElementById("sub").textContent="₱0.00";document.getElementById("tot").textContent="₱0.00";return;}let h="";for(let i in ord){let x=prices[i]*ord[i];s+=x;h+=`<p>${i}×${ord[i]}=₱${x.toFixed(2)}</p>`}e.innerHTML=h;document.getElementById("sub").textContent=`₱${s.toFixed(2)}`;document.getElementById("tot").textContent=`₱${(s+df).toFixed(2)}`}
function clrOrd(){ord={};document.querySelectorAll('input[type="number"]').forEach(i=>i.value=0);document.getElementById("cname").value="";document.querySelector('input[value="pickup"]').checked=true;document.getElementById("locf").style.display="none";updSum()}
function submitOrd(){let n=document.getElementById("cname").value.trim();if(!n||!Object.keys(ord).length)return alert("Fill all fields!");let t=document.querySelector('input[name="ot"]:checked').value,l=document.getElementById("loc").value||"N/A";fetch('/place-order',{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({order:ord,cust_name:n,order_type:t,location:l})}).then(r=>r.json()).then(d=>{if(d.success)showRec(d.receipt),clrOrd()})}
function showRec(r){let it=r.items.map(i=>`<p>${i.n}×${i.q} — ₱${i.s.toFixed(2)}</p>`).join(""),t=r.type==="delivery"?`Delivery to: ${r.loc}`:"Pick Up",h=`<h3 style="text-align:center;color:#ff66b2;font-size:22px">𝙲𝙷𝙾𝚆𝚀𝚄𝙴𝚃𝚃𝙴</h3><p style="text-align:center;font-style:italic">𝒮𝐿𝒜𝒴 𝒮𝒜𝑅𝒜𝒫</p><hr style="border-color:#ffe6f2"><p style="text-align:center">${r.dt}</p><p style="text-align:center"><strong>Customer Name:</strong> ${r.cust_name}</p><p style="text-align:center;font-weight:bold">${t}</p><hr style="border-color:#ffe6f2">${it}<hr style="border-color:#ffe6f2"><p>Subtotal: ₱${r.sub.toFixed(2)}</p>${r.df>0?`<p>Delivery: ₱${r.df.toFixed(2)}</p>`:""}<p><strong>TOTAL: ₱${r.tot.toFixed(2)}</strong></p><hr style="border-color:#ffe6f2"><p style="text-align:center">Thank you 💖</p>`;document.getElementById("rec-body").innerHTML=h;document.getElementById("mod").style.display="block"}
function closeMod(){document.getElementById("mod").style.display="none"}
function viewOrd(){fetch('/get-orders').then(r=>r.json()).then(d=>{document.getElementById("ts").textContent=d.total_sales.toFixed(2);document.getElementById("td").textContent=d.total_delivery.toFixed(2);document.getElementById("sumary").style.display="block";let h=d.orders.length?"":"<p>No orders yet</p>";d.orders.forEach(o=>h+=`<div style="border-bottom:1px solid #ffe6f2;padding:6px 0"><strong>#${o.order_num}</strong> | ${o.dt} | ${o.cust_name} | ${o.type.toUpperCase()} | <strong>₱${o.tot}</strong></div>`);document.getElementById("olist").innerHTML=h})}
function viewRec(){fetch('/get-orders').then(r=>r.json()).then(d=>{let h=d.orders.length?"":"<p>No receipts yet</p>";d.orders.forEach(o=>{let it=o.items.map(i=>`${i.n}×${i.q}=₱${i.s.toFixed(2)}`).join(" | ");h+=`<div style="border-bottom:1px solid #ffe6f2;padding:8px 0"><p><strong>#${o.order_num}</strong> | ${o.dt} | ${o.cust_name}</p><small>${it} | TOTAL: ₱${o.tot.toFixed(2)}</small> <button class="btn pr" style="width:auto;padding:2px 6px;font-size:11px" onclick='showRec(${JSON.stringify(o)})'>View</button></div>`});document.getElementById("rlist").innerHTML=h})}